add hometask-1
equocredite/tank-software-design pull request #1
Opened 2021-09-23 17:45 UTC by equocredite

2021-09-28 20:40 UTC, a-ivanov requested changes

2021-09-28 20:40 UTC, a-ivanov commented on src/main/java/ru/mipt/bit/platformer/Direction.java
> +        ANGLES = Map.of(
Добавьте поля енуму, перенесите туда значения углов и дельты.

2021-09-28 20:40 UTC, a-ivanov commented on src/main/java/ru/mipt/bit/platformer/Direction.java
> +    public static Direction fromKey(int key) {
Перенесите в лаунчер, это конфигурация пользователя, а не данные направления. Их не надо хардкодить в классе.

2021-09-28 20:40 UTC, a-ivanov commented on src/main/java/ru/mipt/bit/platformer/Player.java
> +    private final TextureRegion region;
Перенесите графическую абстракцию обратно в лаунчер / отдельный класс. Здесь - только логика самого игрока как модели (движение, обработка препятствий).

2021-09-28 20:40 UTC, a-ivanov commented on src/main/java/ru/mipt/bit/platformer/Player.java
> +        tileMovement.moveRectangleBetweenTileCenters(rectangle, coordinates, destinationCoordinates, movementProgress);
Перенесите в графическую абстракцию. Туда же все, что связано с текстурой.

2021-09-28 20:40 UTC, a-ivanov commented on src/main/java/ru/mipt/bit/platformer/Renderable.java
> +    Rectangle getRectangle();
Уберите геттеры, отрефакторите интерфейс так, чтобы он умел рисовать себя (а не выставлял наружу свои детали реализации: наличие текстуры, координаты, итд.)

2021-09-28 20:40 UTC, a-ivanov commented on src/main/java/ru/mipt/bit/platformer/Obstacle.java
> +    private final Rectangle rectangle;
См. комментарий к классу игрока, перенесите графическую абстракцию в отдельный класс.

2021-09-28 20:40 UTC, a-ivanov commented on src/main/java/ru/mipt/bit/platformer/GameDesktopLauncher.java
> +    private static final int[] DIRECTION_KEYS = new int[]{RIGHT, UP, LEFT, DOWN, W, A, S, D};
Используйте List.of для создания immutable списка. Боксинг примитивного типа int - тут это экономия на спичках, имьютабилити - важнее.

2021-10-02 20:39 UTC, equocredite commented on src/main/java/ru/mipt/bit/platformer/Direction.java
> +        ANGLES = Map.of(
Здесь не очень понял, можете пояснить подробнее?

2021-10-03 14:55 UTC, a-ivanov requested changes

2021-10-03 14:55 UTC, a-ivanov commented on src/main/java/ru/mipt/bit/platformer/Direction.java
> +        ANGLES = Map.of(
Сейчас вы мапите инстансы енума на значения углов и значения дельт (GridPoint2). ООП решение - это перенести эту информацию в инстанс енума, например: 

```
public enum Direction {
  private final double angle;
  ...

  RIGHT(0f),
  ...
```

См https://docs.oracle.com/javase/tutorial/java/javaOO/enum.html.

2021-10-03 14:56 UTC, a-ivanov commented on src/main/java/ru/mipt/bit/platformer/Direction.java
> +        ANGLES = Map.of(
Сейчас вы мапите инстансы енума на значения углов и значения дельт (GridPoint2). ООП решение - это перенести эту информацию в инстанс енума, например: 

```
public enum Direction {
  private final double angle;
  ...

  RIGHT(0f),
  ...
```

См https://docs.oracle.com/javase/tutorial/java/javaOO/enum.html.

2021-12-15 00:03 UTC, merged