hometask-5
equocredite/tank-software-design pull request #5
Opened 2021-10-28 17:18 UTC by equocredite

2021-11-14 20:11 UTC, a-ivanov requested changes

2021-11-14 20:11 UTC, a-ivanov commented on src/main/java/ru/mipt/bit/platformer/GameDesktopLauncher.java
> +    private Tank player;
Это, bots, obstacles - перенесите в отдельный класс Level, сейчас нарушение SRP. В этом же классе вызывайте обновление этих классов.

2021-11-14 20:11 UTC, a-ivanov commented on src/main/java/ru/mipt/bit/platformer/GameDesktopLauncher.java
> +        player = new Tank(gameObjectMapLoader.getPlayerPosition(),0.4f, collisionManager);
По 3 дз необходимо генерировать случайное положение / считывать из файла.

2021-11-14 20:11 UTC, a-ivanov commented on src/main/java/ru/mipt/bit/platformer/controllers/BotController.java
> +            bot.makeProgress(deltaTime);
Этот вызов - ответственность класса Level. Управление танками-ботами по заданию должен осуществлять контроллер, генерируя команды, управление игроком - команды с клавиатуры.

2021-11-14 20:11 UTC, a-ivanov commented on src/main/java/ru/mipt/bit/platformer/model/Direction.java
> +    public static Direction random(Random rng) {
Перенесите в отдельный утилитный класс/в private AI контроллера. Тут это нарушение SRP.

2021-11-14 20:11 UTC, a-ivanov commented on src/main/java/ru/mipt/bit/platformer/controllers/PlayerKeyboardController.java
> +            player.tryRotateAndStartMovement(calcDirectionFromInputKey(key));
По 4 дз необходимо реализовать паттерн команда.

2021-11-14 20:11 UTC, a-ivanov commented on src/main/java/ru/mipt/bit/platformer/ai/CommandSource.java
> +public interface CommandSource {
Еще необходимо реализовать для нажимаемых клавиш игрока.

2021-11-14 20:11 UTC, a-ivanov commented on src/main/java/ru/mipt/bit/platformer/ai/AwesomeAIAdapter.java
> +    private static GameState buildGameState(Tank player, List<Tank> bots,
Тут проще всего создавать из недостающего класса Level.

2021-11-14 20:11 UTC, a-ivanov commented on src/main/java/ru/mipt/bit/platformer/ai/AwesomeAIAdapter.java
> +        var _player = tankToPlayer(player);
"_" по стандартным конвенциям Java не используется в именах переменных.

2021-11-15 15:49 UTC, equocredite commented on src/main/java/ru/mipt/bit/platformer/GameDesktopLauncher.java
> +        player = new Tank(gameObjectMapLoader.getPlayerPosition(),0.4f, collisionManager);
Здесь просто запрашиваются координаты уже сгенерированные / прочитанные из файла объектом gameObjectMapLoader.

2021-11-18 22:10 UTC, a-ivanov requested changes

2021-11-18 22:10 UTC, a-ivanov commented on src/main/java/ru/mipt/bit/platformer/physics/Level.java
> +    private void createGameObjects() {
Это нарушение SRP, по 3 дз необходимо создавать Level разными способами, тут не должно быть логики по созданию.

2021-12-15 00:03 UTC, merged